version: '3.8'
services:
  cfarm-web:
    container_name: cfarm-party-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8044:80"
    environment:
      - NODE_ENV=production
